version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
    ports: 
      - '5432:5432'
    volumes:
      - ./db/create:/docker-entrypoint-initdb.d/

  turq:
    image: turq:dev
    environment:
      jwt_secret: ${jwt_secret}
      postgres_user: ${postgres_user}
      postgres_pass: ${postgres_password}
      postgres_url: ${postgres_connection_string}
      stripe_key: ${stripe_key}
    depends_on:
      - postgres
    ports:
      - '8000:8000'